// automatically generated by the FlatBuffers compiler, do not modify

export enum ServerTypeEnum {
  None = 0,
  WorldServer = 1,
  BuildingServer = 2,
  ContentsServer = 3,
  MarsTowerServer = 4,
  HouseServer = 5,
  LoginServer = 90,
  CharCreateScene = 91,
  ChattingServer = 92,
  MatchingServer = 99
}
