// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UserHeartBeatClient {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserHeartBeatClient {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserHeartBeatClient(bb:flatbuffers.ByteBuffer, obj?:UserHeartBeatClient):UserHeartBeatClient {
  return (obj || new UserHeartBeatClient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserHeartBeatClient(bb:flatbuffers.ByteBuffer, obj?:UserHeartBeatClient):UserHeartBeatClient {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserHeartBeatClient()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

lastSeqIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

static startUserHeartBeatClient(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addLastSeqIndex(builder:flatbuffers.Builder, lastSeqIndex:number) {
  builder.addFieldInt32(0, lastSeqIndex, 0);
}

static endUserHeartBeatClient(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserHeartBeatClient(builder:flatbuffers.Builder, lastSeqIndex:number):flatbuffers.Offset {
  UserHeartBeatClient.startUserHeartBeatClient(builder);
  UserHeartBeatClient.addLastSeqIndex(builder, lastSeqIndex);
  return UserHeartBeatClient.endUserHeartBeatClient(builder);
}
}
