// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

export class UserHeartBeatServer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):UserHeartBeatServer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsUserHeartBeatServer(bb:flatbuffers.ByteBuffer, obj?:UserHeartBeatServer):UserHeartBeatServer {
  return (obj || new UserHeartBeatServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsUserHeartBeatServer(bb:flatbuffers.ByteBuffer, obj?:UserHeartBeatServer):UserHeartBeatServer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new UserHeartBeatServer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static startUserHeartBeatServer(builder:flatbuffers.Builder) {
  builder.startObject(0);
}

static endUserHeartBeatServer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createUserHeartBeatServer(builder:flatbuffers.Builder):flatbuffers.Offset {
  UserHeartBeatServer.startUserHeartBeatServer(builder);
  return UserHeartBeatServer.endUserHeartBeatServer(builder);
}
}
